title: piurizza
description: Your friendly neighbourhood data engineer
author: Pietro Iurizza
logo: /static/img/avatar.svg
github: https://github.com/piurizza
about: Your friendly neighbourhood data engineer

baseurl: ""
url: "https://www.piurizza.com"

allowsearch: true

share:
  linkedin_username: piurizza 

enableTags: true
categories: [certifications, sql]

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist, jekyll-sitemap]
